require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migrate/**
    - node_modules/**/*
    - bin/**/*
    - tmp/*
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - app/admin/**/*
    - spec/**/*
Lint/MissingSuper:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production